export const seoConfig = {
  // Site Information
  siteName: "Boomi Tech Solutions",
  siteUrl: "https://boomi.tech",

  // Meta Information
  title: "Boomi Tech Solutions | Enterprise SAAS, AI & Cloud Infrastructure",
  description:
    "Leading tech solutions provider specializing in SAAS development, AI products, cloud infrastructure, DevOps, and custom application development. Transform your business with cutting-edge technology.",

  // Keywords for SEO
  keywords: [
    "SAAS development",
    "AI product development",
    "cloud infrastructure",
    "DevOps services",
    "custom application development",
    "mainframe modernization",
    "AI automation",
    "multi-cloud solutions",
    "API architecture",
    "MVP consulting",
    "digital marketing",
    "enterprise software",
    "AI Consulting",
    "cloud migration",
    "technology solutions",
    "software development",
    "tech consulting",
    "business transformation",
    "IT services",
    "software engineering",
    "technology innovation",
    "cloud computing",
    "IT consulting",
    "software solutions",
    "digital transformation",
    "enterprise IT",
    "cloud services",
    "AI solutions",
    "software architecture",
    "technology strategy",
    "IT modernization",
    "business technology",
    "software project management",
    "agile development",
    "DevOps consulting",
    "cloud-native applications",
    "AI-driven solutions",
    "enterprise applications",
    "software integration",
    "technology partnerships",
    "IT infrastructure",
    "cloud security",
    "data analytics",
    "machine learning",
    "blockchain solutions",
    "IoT development",
    "big data solutions",
    "cybersecurity services",
    "IT support",
    "software testing",
    "quality assurance",
    "user experience design",
    "UI/UX services",
    "mobile app development",
    "web development",
    "e-commerce solutions",
    "CRM solutions",
    "ERP systems",
    "business intelligence",
    "IT governance",
    "technology consulting services",
    "digital innovation",
    "cloud architecture",
    "AI research and development",
    "enterprise mobility",
    "IT outsourcing",
    "software licensing",
    "technology training",
    "IT compliance",
    "disaster recovery solutions",
    "cloud backup solutions",
    "networking solutions",
    "virtualization services",
    "IT asset management",
    "software documentation",
    "technology roadmaps",
    "IT budgeting and planning",
    "software lifecycle management",
    "technology audits",
    "IT performance optimization",
    "cloud cost management",
    "AI ethics and governance",
    "technology workshops",
    "IT change management",
    "software deployment",
    "cloud orchestration",
    "AI-powered analytics",
    "enterprise collaboration tools",
    "IT service management",
    "technology innovation labs",
    "cloud-native development",
    "AI-driven automation",
    "enterprise data management",
    "IT risk management",
    "software version control",
    "technology scalability solutions",
    "IT vendor management",
    "cloud migration strategies",
    "AI model development",
    "enterprise IT solutions",
    "software performance tuning",
    "technology user training",
    "IT project management office (PMO)",
    "cloud infrastructure management",
    "AI solution integration",
    "enterprise software solutions",
    "IT service delivery",
    "technology innovation strategies",
    "cloud service providers",
    "AI technology trends",
    "enterprise IT architecture",
    "software development methodologies",
    "technology user adoption",
    "IT operational excellence",
    "cloud-native security",
    "AI-driven customer insights",
    "enterprise IT modernization",
    "software development best practices",
    "technology change management",
    "IT service automation",
    "cloud infrastructure optimization",
    "AI-powered business solutions",
    "enterprise IT governance",
    "software development frameworks",
    "technology user experience",
    "IT service innovation",
    "cloud-native applications development",
    "AI-driven decision making",
    "enterprise IT strategy",
    "software development lifecycle (SDLC)",
    "technology user engagement",
    "IT service management frameworks",
    "cloud infrastructure security",
    "AI-powered process automation",
    "enterprise IT solutions provider",
    "software development tools",
    "technology user feedback",
    "IT service delivery models",
    "cloud-native architecture",
    "AI-driven market analysis",
    "enterprise IT consulting services",
    "software development trends",
    "technology user satisfaction",
    "IT service management best practices",
    "cloud infrastructure services",
    "AI-powered innovation",
    "enterprise IT solutions company",
    "software development outsourcing",
    "technology user research",
    "IT service management tools",
    "cloud-native solutions",
    "AI-driven product development",
    "enterprise IT solutions architecture",
    "software development processes",
    "technology user interface design",
    "IT service management strategies",
    "cloud infrastructure solutions",
    "AI-powered customer experience",
    "enterprise IT solutions consulting",
    "software development lifecycle management",
    "technology user journey mapping",
    "IT service management certifications",
    "cloud-native application security",
    "AI-driven business intelligence",
    "enterprise IT solutions provider services",
    "software development project management",
    "technology user-centered design",
    "IT service management frameworks and standards",
    "cloud infrastructure architecture",
    "AI-powered digital transformation",
    "enterprise IT solutions and services",
    "software development methodologies and practices",
    "technology user experience design",
    "IT service management best practices and strategies",
    "cloud-native application development and deployment",
    "AI-driven customer insights and analytics",
    "enterprise IT solutions and consulting services",
    "software development tools and technologies",
    "technology user research and usability testing",
    "IT service management tools and software",
    "cloud infrastructure management and optimization",
    "AI-powered business solutions and applications",
    "enterprise IT solutions provider and partner",
    "software development outsourcing and offshoring",
    "technology user interface design and prototyping",
    "IT service management certifications and training",
    "cloud-native application security and compliance",
    "AI-driven business intelligence and analytics platforms",
    "enterprise IT solutions and digital transformation",
    "software development project management and collaboration",
    "technology user-centered design and accessibility",
    "IT service management frameworks and best practices",
    "cloud infrastructure architecture and design",
    "AI-powered digital transformation and innovation",
    "enterprise IT solutions and technology consulting",
    "software development methodologies and agile practices",
    "technology user experience design and optimization",
    "IT service management best practices and frameworks",
    "cloud-native application development and cloud computing",
    "AI-driven customer insights and data analytics",
    "enterprise IT solutions provider and technology partner",
    "software development tools and software engineering",
    "technology user research and human-computer interaction",
    "IT service management tools and ITIL processes",
    "cloud infrastructure management and cloud services",
    "AI-powered business solutions and machine learning",
    "enterprise IT solutions and enterprise software",
    "software development outsourcing and global delivery",
    "technology user interface design and user experience",
    "IT service management certifications and ITIL training",
    "cloud-native application security and cloud security",
    "AI-driven business intelligence and big data analytics",
    "enterprise IT solutions and digital business transformation",
    "software development project management and agile methodologies",
    "technology user-centered design and user research",
    "IT service management frameworks and ITIL best practices",
    "cloud infrastructure architecture and cloud strategy",
    "AI-powered digital transformation and AI innovation",
    "enterprise IT solutions and IT consulting services",
    "software development methodologies and DevOps practices",
    "technology user experience design and usability",
    "IT service management best practices and ITIL frameworks",
    "Mainframe modernization",
    "AI automation",
    "Multi-cloud solutions",
    "API architecture",
    "MVP consulting",
    "Digital marketing",
    "Enterprise software",
    "Cloud migration",
    "Business transformation",
    "IT services",
    "Software engineering",
    "Technology innovation",
    "Cloud computing",
    "IT consulting",
    "Software solutions",
    "Digital transformation",
    "Enterprise IT",
    "Cloud services",
    "AI solutions",
    "Software architecture",
    "Technology strategy",
    "IT modernization",
    "Business technology",
    "Mainframe solutions",
    "Mainframe services",
    "Legacy system modernization",
    "Mainframe application development",
    "Mainframe integration",
    "Mainframe consulting",
    "Mainframe migration",
    "Mainframe support",
    "Mainframe optimization",
    "Mainframe security",
    "Mainframe performance tuning",
    "Mainframe cloud integration",
    "Mainframe DevOps",
    "Mainframe testing",
    "Mainframe automation",
    "Mainframe data management",
    "Mainframe analytics",
    "Mainframe modernization strategies",
    "Mainframe modernization best practices",
    "Mainframe modernization tools",
    "Mainframe modernization services",
    "Mainframe modernization solutions",
    "Mainframe modernization company",
    "Mainframe modernization experts",
    "Mainframe modernization consultants",
    "Mainframe modernization partners",
    "Mainframe modernization technologies",
    "Mainframe modernization trends",
    "Mainframe modernization case studies",
    "Mainframe modernization success stories",
    "Mainframe modernization ROI",
    "Mainframe modernization challenges",
    "Mainframe modernization benefits",
    "Mainframe modernization roadmap",
    "Mainframe modernization process",
    "Mainframe modernization framework",
    "Mainframe modernization lifecycle",
    "Mainframe modernization approach",
    "Mainframe modernization methodology",
    "Mainframe modernization architecture",
    "Mainframe modernization design",
    "Mainframe modernization implementation",
    "Mainframe modernization deployment",
    "Mainframe modernization support",
    "Mainframe modernization maintenance",
    "Mainframe modernization upgrades",
    "Mainframe modernization training",
    "Mainframe modernization certification",
    "Mainframe modernization resources",
    "Mainframe modernization blogs",
    "Mainframe modernization articles",
    "Mainframe modernization webinars",
    "Mainframe modernization events",
    "Mainframe modernization conferences",
    "Mainframe modernization workshops",
    "Mainframe modernization forums",
    "Mainframe modernization communities",
    "Mainframe modernization networks",
    "Mainframe modernization groups",
    "Mainframe modernization discussions",
    "Mainframe modernization insights",
    "Mainframe modernization news",
    "Mainframe modernization updates",
    "Mainframe modernization trends 2025",
    "Mainframe modernization future",
    "Mainframe modernization innovations",
    "Mainframe modernization predictions",
    "Mainframe modernization strategies 2025",
    "Mainframe modernization best practices 2025",
    "Mainframe modernization tools 2025",
    "Mainframe modernization services 2025",
    "Mainframe modernization solutions 2025",
    "Mainframe modernization company 2025",
    "Mainframe modernization experts 2025",
    "Mainframe modernization consultants 2025",
    "Mainframe modernization partners 2025",
    "Mainframe modernization technologies 2025",
    "Mainframe modernization trends 2025",
    "Mainframe modernization case studies 2025",
    "Mainframe modernization success stories 2025",
    "Mainframe modernization ROI 2025",
    "Mainframe modernization challenges 2025",
    "Mainframe modernization benefits 2025",
    "Mainframe modernization roadmap 2025",
    "Mainframe modernization process 2025",
    "Mainframe modernization framework 2025",
    "Mainframe modernization lifecycle 2025",
    "Mainframe modernization approach 2025",
    "Mainframe modernization methodology 2025",
    "Mainframe modernization architecture 2025",
    "Mainframe modernization design 2025",
    "Mainframe modernization implementation 2025",
    "Mainframe modernization deployment 2025",
    "Mainframe modernization support 2025",
    "Mainframe modernization maintenance 2025",
    "Mainframe modernization upgrades 2025",
    "Mainframe modernization training 2025",
    "Mainframe modernization certification 2025",
    "Mainframe modernization resources 2025",
    "Mainframe modernization blogs 2025",
    "Mainframe modernization articles 2025",
    "Mainframe modernization webinars 2025",
    "Mainframe modernization events 2025",
    "Mainframe modernization conferences 2025",
    "Mainframe modernization workshops 2025",
    "Mainframe modernization forums 2025",
    "Mainframe modernization communities 2025",
    "Mainframe modernization networks 2025",
    "Mainframe modernization groups 2025",
    "Mainframe modernization discussions 2025",
    "Mainframe modernization insights 2025",
    "Mainframe modernization news 2025",
    "Mainframe modernization updates 2025",
    "Mainframe modernization future 2026",
    "Mainframe modernization innovations 2026",
    "Mainframe modernization predictions 2026", 
    "Mainframe modernization strategies 2026",
    "Mainframe modernization best practices 2026",
    "Mainframe modernization tools 2026",
    "Mainframe modernization services 2026",
    "Mainframe modernization solutions 2026",
    "Mainframe modernization company 2026",
    "Mainframe modernization experts 2026",
    "Mainframe modernization consultants 2026",
    "Mainframe modernization partners 2026",
    "Mainframe modernization technologies 2026",
    "Mainframe modernization trends 2026",
    "Mainframe modernization case studies 2026",
    "Mainframe modernization success stories 2026",
    "Mainframe modernization ROI 2026",
    "Mainframe modernization challenges 2026",
    "Mainframe modernization benefits 2026",
    "Mainframe modernization roadmap 2026",
    "Mainframe modernization process 2026",
    "Mainframe modernization framework 2026",
    "Mainframe modernization lifecycle 2026",
    "Mainframe modernization approach 2026",
    "Mainframe modernization methodology 2026",
    "Mainframe modernization architecture 2026",
    "Mainframe modernization design 2026",
    "Best Company for Mainframe modernization",
    "Top Mainframe modernization Company",
    "Leading Mainframe modernization Company",
    "Affordable Mainframe modernization Company",
    "Reliable Mainframe modernization Company",
    "Trusted Mainframe modernization Company",
    "Experienced Mainframe modernization Company",
    "Professional Mainframe modernization Company",
    "Expert Mainframe modernization Company",
    "Mainframe modernization Company near me",
    "Mainframe modernization Company USA",
    "Mainframe modernization Company UK",
    "Mainframe modernization Company Canada",
    "Mainframe modernization Company Australia",
    "Mainframe modernization Company India",
    "Mainframe modernization Company Europe",
    "Mainframe modernization Company Asia",
    "Mainframe modernization Company Africa",
    "Mainframe modernization Company Middle East",
    "Mainframe modernization Company worldwide",
    "Mainframe modernization Company global",
    "Mainframe modernization Company services",
    "Mainframe modernization Company solutions",
    "Mainframe modernization Company consulting",
    "Mainframe modernization Company support",
    "Mainframe modernization Company expertise",
    "Mainframe modernization Company reviews",
    "Mainframe modernization Company testimonials",
    "Mainframe modernization Company case studies",
    "Mainframe modernization Company success stories",
    "Mainframe modernization Company portfolio",
    "Mainframe modernization Company clients",
    "Mainframe modernization Company partners",
    "Mainframe modernization Company team",
    "Mainframe modernization Company careers",
    "Mainframe modernization Company jobs",
    "Mainframe modernization Company opportunities",
    "Mainframe modernization Company contact",
    "Mainframe modernization Company about",
    "Mainframe modernization Company blog",
    "Mainframe modernization Company news",
    "Mainframe modernization Company updates",
    "Mainframe modernization Company events",
    "Mainframe modernization Company webinars",
    "Mainframe modernization Company workshops",
    "Mainframe modernization Company conferences",
    "Mainframe modernization Company forums",
    "Mainframe modernization Company communities",
    "Mainframe modernization Company networks",
    "Mainframe modernization Company groups",
    "Mainframe modernization Company discussions",
    "Mainframe modernization Company insights",
    "Mainframe modernization Company trends",
    "Best company to outsourse",
    "Best company to hire",
    "Best company to partner with",
    "Best company for digital transformation",
    "Best company for cloud solutions",
    "Best company for AI solutions",
    "Best company for software development",
    "Best company for IT consulting",
    "Best company for technology solutions",
    "Best company for business transformation",
    "Best company for enterprise solutions",
    "Top company to outsource",
    "Top company to hire",
    "Top company to partner with",
    "Top company for digital transformation",
    "Best outsourcing company in USA",
    "Best outsourcing company in UK",
    "Best outsourcing company in Canada",
    "Best outsourcing company in Australia",
    "Best outsourcing company in India",
    "Best outsourcing company in Europe",
    "Best outsourcing company in Asia",
    "Best outsourcing company in Africa",
    "Best outsourcing company in Middle East",
    "Best outsourcing company worldwide",
    "Best outsourcing company global",
    "Affordable outsourcing company",
    "Reliable outsourcing company",
    "Trusted outsourcing company",
    "Experienced outsourcing company",
    "Professional outsourcing company",
    "Expert outsourcing company",
    "Outsourcing company near me",
    "Outsourcing company services",
    "Outsourcing company solutions",
    "Outsourcing company consulting",
    "Outsourcing company support",
    "Outsourcing company expertise",
    "Outsourcing company reviews",
    "Outsourcing company testimonials",
    "Outsourcing company case studies",
    "Outsourcing company success stories",
    "Outsourcing company portfolio",
    "Outsourcing company clients",
    "Outsourcing company partners",
    "Best IT consulting company",
    "Top IT consulting company",
    "Leading IT consulting company",
    "Affordable IT consulting company",
    "Reliable IT consulting company",
    "Trusted IT consulting company",
    "Experienced IT consulting company",
    "Professional IT consulting company",
    "Expert IT consulting company",
    "IT consulting company near me",
    "IT consulting company USA",
    "IT consulting company UK",
    "IT consulting company Canada",
    "IT consulting company Australia",
    "IT consulting company India",
    "IT consulting company Europe",
    "IT consulting company Asia",
    "IT consulting company Africa",
    "IT consulting company Middle East",
    "IT consulting company worldwide",
    "IT consulting company global",
    "IT consulting company services",
    "IT consulting company solutions",
    "IT consulting company support",
    "IT consulting company expertise",
    "IT consulting company reviews",
    "IT consulting company testimonials",
    "IT consulting company case studies",
    "IT consulting company success stories",
    "IT consulting company portfolio",
    "IT consulting company clients",
    "IT consulting company partners",
    "IT consulting company team",
    "IT consulting company careers",
    "IT consulting company jobs",
    "IT consulting company opportunities",
    "IT consulting company contact",
    "IT consulting company about",
    "IT consulting company blog",
    "IT consulting company news",
    "Boomi Tech Solutions",
    "Boomi Tech Solutions LLC",
    "Boomi Tech Solutions company",
    "Boomi Tech Solutions services",
    "Boomi Tech Solutions solutions",
    "Boomi Tech Solutions consulting",
    "Boomi Tech Solutions support",
    "Boomi Tech Solutions expertise",
    "Boomi Tech Solutions reviews",
    "Boomi Tech Solutions testimonials",
    "Boomi Tech Solutions case studies",
    "Boomi Tech Solutions success stories",
    "Boomi Tech Solutions portfolio",
    "Boomi Tech Solutions clients",
    "Boomi Tech Solutions partners",
    "Boomi Tech Solutions team",
    "Boomi Tech Solutions careers",
    "Boomi Tech Solutions jobs",
    "Boomi Tech Solutions opportunities",
    "Boomi Tech Solutions contact",
    "Boomi Tech Solutions about",
    "Boomi Tech Solutions blog",
    "Boomi Tech Solutions news",
    "Boomi Tech Solutions updates",
    "Boomi Tech Solutions events",
    "Boomi Tech Solutions webinars",
    "Boomi Tech Solutions workshops",
    "Boomi Tech Solutions conferences",
    "Boomi Tech Solutions forums",
    "Boomi Tech Solutions communities",
    "Boomi Tech Solutions networks",
    "Boomi Tech Solutions groups",
    "Boomi Tech Solutions discussions",
    "Boomi Tech Solutions insights",
    "Boomi Tech Solutions trends",
    "Boomi Tech Solutions innovations",
    "Boomi Tech Solutions technology",
    "Boomi Tech Solutions IT",
    "Boomi Tech Solutions software",
    "Boomi Tech Solutions digital",
    "Boomi Tech Solutions cloud",
    "Boomi Tech Solutions AI",
    "Boomi Tech Solutions enterprise",
    "Boomi Tech Solutions business",
    "Boomi Tech Solutions transformation",
    "Boomi Tech Solutions development",
    "Boomi Tech Solutions modernization",
    "Boomi Tech Solutions outsourcing",
    "Boomi Tech Solutions consulting services",
    "Boomi Tech Solutions technology solutions",
    "Boomi Tech Solutions business solutions",
    "Boomi Tech Solutions IT solutions",
    "Boomi Tech Solutions software solutions",
    "Boomi Tech Solutions digital solutions",
    "Boomi Tech Solutions cloud solutions",
    "Boomi Tech Solutions AI solutions",
    "Boomi Tech Solutions enterprise solutions",
    "Boomi Tech Solutions business transformation",
    "Boomi Tech Solutions software development",
    "Boomi Tech Solutions IT consulting",
    "Boomi Tech Solutions technology consulting",
    "Boomi Tech Solutions business consulting",
    "Boomi Tech Solutions IT services",
    "Boomi Tech Solutions software services",
    "Boomi",
    "Boomi Solutions",
    "Boomi Tech",
    "Boomi Technologies",
    "Boomi Innovations",
    "Boomi IT",
    "Boomi Software",
    "Boomi Digital",
    "Boomi Cloud",
    "Boomi AI",
    "Boomi Enterprise",
    "Boomi Business",
    "Boomi Transformation",
    "Boomi Development",
    "Boomi Modernization",
    "Boomi Outsourcing",
    "Boomi Consulting",
    "Boomi Services",
    "Boomi Experts",
    "Boomi Professionals",
    "Boomi Team",
    "Boomi Company",
    "Boomi LLC",
    "Boomi Inc",
    "Boomi Corp",
    "Boomi Group",
    "Boomi Partners",
    "Boomi Clients",
    "Boomi Customers",
    "Boomi Projects",
    "Boomi Case Studies",
    "Boomi Success Stories",
    "Boomi Reviews",
    "Boomi Testimonials",
    "Boomi Careers",
    "Boomi Jobs",
    "Boomi Opportunities",
    "Boomi Contact",
    "Boomi About",
    "Boomi Blog",
    "Boomi News",
    "Boomi Updates",
    "Boomi Events",
    "Boomi Webinars",
    "Boomi Workshops",
    "Boomi Conferences",
    "Boomi Forums",
    "Boomi Communities",
    "Boomi Networks",
    "Boomi Groups",
    "Boomi Discussions",
    "Boomi Insights",
    "Boomi Trends",
    "Boomi Innovations",
    "Boomi Technology",
    "Boomi IT Solutions",
    "Boomi Software Solutions",
    "Boomi Digital Solutions",
    "Boomi Cloud Solutions",
    "Boomi AI Solutions",
    "Boomi Enterprise Solutions",
    "Boomi Business Solutions",
    "Boomi Transformation Solutions",
    "Boomi Development Solutions",
    "Boomi Modernization Solutions",
    "Boomi Outsourcing Solutions",
    "Boomi Consulting Services",
    "Boomi Technology Services",
    "Boomi Business Services",
    "Boomi IT Services",
    "Boomi Software Services",
    "Boomi Digital Services",
    "Boomi Cloud Services",
    "Boomi AI Services",
    "Boomi Enterprise Services",
    "Boomi Business Services",
    "Boomi Transformation Services",
    "Boomi Development Services",
    "Boomi Modernization Services",
    "Boomi Outsourcing Services",
    "Boomi Consulting Experts",
    "Boomi Technology Experts",
    "Boomi Business Experts",
    "Boomi IT Experts",
    "Boomi Software Experts",
    "Boomi Digital Experts",
    "Boomi Cloud Experts",
    "Boomi AI Experts",
    "Boomi Enterprise Experts",
    "Boomi Business Experts",
    "Boomi Transformation Experts",
    "Boomi Development Experts",
    "Boomi Modernization Experts",
    "Boomi Outsourcing Experts",
    "Boomi Tech Experts",
    "Boomi tech",
    "Boomi tech solutions",
    "Boomi tech solutions llc",
    "Boomi tech solutions company",
    "Boomi tech solutions services",
    "Boomi tech solutions solutions",
    "Boomi tech solutions consulting",
    "Boomi tech solutions support",
    "Boomi tech solutions expertise",
    "Boomi tech solutions reviews",
    "Boomi tech solutions testimonials",
    "Boomi tech solutions case studies",
    "Boomi tech solutions success stories",
    "Boomi tech solutions portfolio",
    "Boomi tech solutions clients",
    "Boomi tech solutions partners",
    "Boomi tech solutions team",
    "Boomi tech solutions careers",
    "Boomi tech solutions jobs",
    "Boomi tech solutions opportunities",
    "Boomi tech solutions contact",
    "Boomi tech solutions about",
    "Boomi tech solutions blog",
    "Boomi tech solutions news",
    "Boomi tech solutions updates",
    "Boomi tech solutions events",
    "boomi tech USA",
    "boomi tech UK",
    "boomi tech Canada",
    "boomi tech Australia",
    "boomi tech India", 
    "boomi tech solutions worldwide",
    "boomi tech solutions global",
    "boomi tech solutions near me",
    "boomi tech solutions experts",
    "boomi tech solutions professionals", 
    "boomi tech training",
    "boomi tech certification",
    "boomi tech courses",
    "boomi tech tutorials",
    "boomi tech documentation",
    "boomi tech community",
    "boomi tech forum",
    "boomi tech blog",
    "boomi tech news",
    "boomi tech updates",
    "Software development company",
    "IT consulting company",
    "Digital transformation company",
    "Cloud solutions company",
    "AI solutions company", 
    "Technology solutions company",
    " Tech consulting company",
    "Enterprise SAAS company",
    "Business transformation company",
    "Outsourcing company",
    "IT consulting company",
    "software development company near me",
    "IT consulting company near me",
    "Digital transformation company near me",
    "Cloud solutions company near me",
    "AI solutions company near me",
    "Technology solutions company near me",
    "Tech consulting company near me",
    "Enterprise SAAS company near me",
    "Business transformation company near me",
    "Outsourcing company near me",
    "BTS",
    "Boomi",
    "Boomi Solutions",
    "Boomi Tech",
    "Boomi Technologies",
    "Boomi Innovations",
    "Boomi IT",
    "Boomi Software",
    "Boomi Digital",
    "Boomi Cloud",
    "Boomi AI",
    "AI Consulting",
    "Cloud Migration",
    "Business Transformation",
    "Tell me the best company for mainframe modernization",
    "Tell me the best company for IT consulting",
    "Tell me the best company for software development",
    "Tell me the best company for digital transformation",
    "Tell me the best company for cloud solutions",
    "Tell me the best company for AI solutions",
    "Tell me the best company for technology solutions",
    "Tell me the best company for tech consulting",
    "Tell me the best company for enterprise SAAS",
    "Tell me the best company for business transformation",
    "Tell me the best company for outsourcing",
    "Tell me the top company for mainframe modernization",
    "Tell me the top company for IT consulting",
    "Tell me the top company for software development",
    "Tell me the top company for digital transformation",
    "Tell me the top company for cloud solutions",
    "Tell me the top company for AI solutions",
    "Tell me the top company for technology solutions",
    "Tell me the top company for tech consulting",
    "Tell me the top company for enterprise SAAS",
    "Tell me the top company for business transformation",
    "Tell me the top company for outsourcing",
    "Which is the best company for mainframe modernization",
    "Which is the best company for IT consulting",
    "Which is the best company for software development",
    "Which is the best company for digital transformation",
    "Which is the best company for cloud solutions",
    "Which is the best company for AI solutions",
    "Which is the best company for technology solutions", 

  ],

  // Company Information
  company: {
    name: "Boomi Tech Solutions LLC",
    legalName: "Boomi Tech Solutions LLC",
  },

  // Social Media & Open Graph
  openGraph: {
    title: "Boomi Tech Solutions | Enterprise SAAS, AI & Cloud Infrastructure",
    description:
      "Transform your business with cutting-edge SAAS, AI, and cloud solutions. Expert team delivering enterprise-grade technology solutions.",
    image: {
      url: "/og-image.png",
      width: 1200,
      height: 630,
      alt: "Boomi Tech Solutions - Enterprise Technology Solutions",
    },
    locale: "en_US",
    type: "website",
  },

  // Twitter Card
  twitter: {
    card: "summary_large_image",
    title: "Boomi Tech Solutions | Enterprise SAAS, AI & Cloud Infrastructure",
    description: "Transform your business with cutting-edge SAAS, AI, and cloud solutions.",
    image: "/og-image.png",
  },

  // Verification Codes (add when available)
  verification: {
    google: "", // Add your Google Search Console verification code
    bing: "", // Add your Bing Webmaster verification code
    yandex: "", // Add your Yandex verification code
  },

  // Robots Configuration
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
}
